### ISSUE TITLE
XML error — moving to Slinkity

### ISSUE THREAD

**Issue by kylesloper** [slinkity/slinkity#84] opened 2021-11-13 15:21 UTC
Our team has begun a migration to Slinkity purely for the Vite x Eleventy workflow as advised by @bholmesdev. We are currently testing it out on our Eleventy boilerplate and receive this error:

```
Stacktrace:
Cannot read property 'insertAdjacentHTML' of null
[Error] We failed to render components used in file src
We recommend trying to:
delete your output directory and restart the server / build
clear your node_modules and running a clean install with "npm i"
Visit https://slinkity.dev to review our changelogs!
```

Slinkity then serves the site at `localhost:8080` but on page visit the CLI throws another error:
```
 Unable to parse {"file":"/index.html","line":161,"column":10}
```
With no logical reason to why this syntax is parsed incorrectly.

**To Reproduce**

1. Clone [this ](https://github.com/kylesloper/discord-slinkity)repo
2. `npm i`
3. `npm run start`

 - Win 10 x64
 - Chredge v95

I was told that @AndrewLeedham has done some good work with #65 and might offer some good opinions.

Thanks all,

**Comment by AndrewLeedham** [comment] 2021-11-15 15:08
Hi @kylesloper. The XML errors seem to be coming from your SVG files that all include `<?xml version="1.0" encoding="utf-8"?>` at the top.

I would hazard a guess that Vite is trying to inline your SVGs and thus parsing them as HTML which in that context the XML shebang is invalid.

I guess the simple fix would be to just remove the shebang, or if you don't want Vite to inline the SVG you could use https://vitejs.dev/guide/assets.html#explicit-url-imports

**Comment by AleksandrHovhannisyan** [comment] 2021-11-16 11:41
@AndrewLeedham I'm also trying to run the slinkity server and getting the same error, probably for the same reason (I'm using NPM packages that inline SVG strings, and they contain the namespace declaration).

I can't quite figure out from the Vite docs what the solution would be in this case; could you clarify what it might look like?

**Comment by AndrewLeedham** [comment] 2021-11-16 12:04
Hi @AleksandrHovhannisyan. Curious what package you are using, is it adding the XML shebang itself or do you have it in your raw SVG files. Perhaps the package should be stripping it out?

The problem boils down to Vite parsing HTML with a library called `@vue/compiler-dom` which is strict on what is HTML unlike 11ty which is very lax. You can play with the parsing here: https://runkit.com/embed/vu8bhm0jpbi9

**Comment by AleksandrHovhannisyan** [comment] 2021-11-16 12:39
Oh, my bad, I was remembering wrong; my SVGs don't have `<?xml version="1.0" encoding="utf-8"?>`.

So maybe it's a different issue on my end. Will see if I can push up a test branch and open a separate issue, but it may be difficult to debug since my site is big.

**Comment by AndrewLeedham** [comment] 2021-11-16 12:44
If you can isolate the issue in a separate repro site that would be very useful :) E.g: forking the base blog and adding your SVG stuff to it like: https://github.com/AndrewLeedham/eleventy-base-blog-slinkity

**Comment by brycewray** [comment] 2021-11-16 13:48
FWIW, I replaced all my [repo](https://github.com/brycewray/eleventy-slinkity-test)'s SVGs with HTML entities and it reduced the number of these `We failed to render`/`Cannot read property 'insertAdjacentHTML'` messages down to only one per build. Don't know if that helps, but just putting it out there.

**Comment by Holben888** [comment] 2021-11-16 14:28
So from my experience with this error, it is _not_ related to Vite! It's actually the [node html parser](https://www.npmjs.com/package/node-html-parser) lib we're using to append live reload scripts to the `body` tag. We auto-wrap every page in `html` and `body` tags though, so I'm not sure why it fails when appending to the body. We might need to investigate a new HTML parser for this!

**Comment by AndrewLeedham** [comment] 2021-11-16 14:36
I agree, although I think there are 2 issues here. The `Cannot read property 'insertAdjacentHTML' of null` does not seem related to Vite and does need some investigation. But the `Unable to parse {"file":"/index.html","line":161,"column":10}` error seems to be to do with the XML shebang, there was more information below that error message when running locally.

Also something I noticed when running locally @kylesloper one of your files has 2 `class` declarations which causes a completely different Vite error, but it does not actually show why it fails in the console, so that might need investigating separately (The error only shows up after removing all the XML shebangs).

**Comment by Holben888** [comment] 2021-11-19 02:56
@AndrewLeedham Fair callouts there! As for the `insertAdjacementHTML` issue, I'm considering just... ditching our HTML parsing entirely. We only use the parser for:
- inserting `script` tags within the `body`
- SSR-ing the correct elements on the page at buildtime

We can solve the former by generating the `script` tag within each shortcode output itself. Sure, they won't group neatly at the bottom of the page. But Vite runs through and optimizes all these script tags anyways... so who cares where they are on the page?

The latter could be solved with a comment + some unique hash that we can match on the raw string output. [Vite's own demo of SSR](https://vitejs.dev/guide/ssr.html#setting-up-the-dev-server) uses a simple `.replace` on a comment string. I imagine we could do something similar, just with a fancy hash thrown in to prevent users from accidentally busting our builds. 

node-html-parser released 1 breaking change during Slinkity development (see #66), so they've already breached my trust in the library. Also not a fan of the performance hit Cheerio could bring. So maybe just simplify here 🤷

**Comment by ajcwebdev** [comment] 2021-11-19 04:09
I think the more we can reduce unneeded dependencies the better and both those work arounds sound very minimal and non-hacky to me.

**Comment by AndrewLeedham** [comment] 2021-12-13 21:28
I did some more digging on the `insertAdjacementHTML` piece. And it looks like you are building your `src/components` folder @kylesloper, this looks like a mistake as the components seem like partials/includes which don't have layouts, this might be relevant: https://www.11ty.dev/docs/config/#directory-for-includes. So they are rendered without any `<html>` or `<body>` 11ty then seems to just be adding a wrapping `<html>` tag which then fails [this check](https://github.com/slinkity/slinkity/blob/76715902291289d90dddc02685779c39dc01d12b/src/plugin/reactPlugin/2-pageTransform/applyHtmlWrapper.js#L13) and a body is never added, hence the error.

@Holben888 I agree moving to an approach that does not require adding structured markup to the page seems logical. Outputting as close to what 11ty seems like the goal, and I don't believe they add a `<body>`.

The "XML shebang in SVG" and "duplicate class name" issue seems to be a symptom of Vite being more strict on valid syntax compared to 11ty. There doesn't seem like an easy way around this right now, so perhaps a feature request to Vite for a lax mode?

**Comment by kylesloper** [comment] 2021-12-18 16:57
Thanks for that extra research there @AndrewLeedham. I completely agree with you Slinkity needs to be at a place where it is outputting as close to 11ty syntax as possible to avoid issues like this in the future.

However for the situation at hand, how do you suggest I stop `src/components` from being built. 

As the 11ty docs describe,  "[Includes] files will not be processed as full template files, but can be consumed by other templates." So doesn't that mean that `components` shouldn't be built according to file config.

I'll paste my dir config down below for reference but I don't know why the wrapping of `<html>` is occuring.
```
    dir: {
      input: 'src',
      output: ".www",
      data: '_data',
      includes: 'components',
      layouts: 'layouts',
    }
```

Cheers.

**Comment by AndrewLeedham** [comment] 2021-12-18 17:08
> Thanks for that extra research there @AndrewLeedham. I completely agree with you Slinkity needs to be at a place where it is outputting as close to 11ty syntax as possible to avoid issues like this in the future.
> 
> However for the situation at hand, how do you suggest I stop `src/components` from being built.
> 
> As the 11ty docs describe, "[Includes] files will not be processed as full template files, but can be consumed by other templates." So doesn't that mean that `components` shouldn't be built according to file config.
> 
> I'll paste my dir config down below for reference but I don't know why the wrapping of `<html>` is occuring.
> 
> ```
>     dir: {
>       input: 'src',
>       output: ".www",
>       data: '_data',
>       includes: 'components',
>       layouts: 'layouts',
>     }
> ```
> 
> Cheers.

@kylesloper Apologies I missed that you had `includes: 'components',` in your eleventy config. That theory is debunked then. `<html>` is being added around the component somehow though, more investigation to follow..

**Comment by Holben888** [comment] 2022-01-02 22:14
Okay _so,_ I'm happy to share this issue's near the finish line! We've successfully removed our HTML parser library, without any regressions on component hydration 👍 

However, a recent PR throws a wrench into how we handle style imports via ESM: #113 The last listed change is our issue:
> inject each imported style as a `<link>` in the `head`

[This was trivial with our HTML parser in place](https://github.com/slinkity/slinkity/pull/113/files#diff-45e596696b455a5399cf97570e51da497c32e2639648509ffe0bdea5c1e77bf6R45-R57). But how can we inject stylesheets into the `head` without a true parser? Well, these are the options I've found.

## 1. Apply stylesheets to the page with `<script>` tags instead

This is first approach I tried in that PR. We're just trying to SSR your components that _already_ import styles via ESM. So why not turn a component like this:

```jsx
import './styles.scss'
export default function Component() {
  return <p>cool</p>
}
```

Into server-rendered output like this?

```html
<script type="module">
  import '/resolved/styles.scss'
</script>
<p>cool</p>
```

This works well for production builds actually, but we run into trouble from the dev server side. Here's the deubgging experience:

![demo of injecting styles with `script` tags](https://user-images.githubusercontent.com/31811199/147890379-efecac58-c3fb-4931-9bc6-ff467111bb17.gif)

1. **There's a flash of unstyled content** as Vite resolves the import. This won't happen in production, but it's not great for dev experience
2. **Adding and removing styles has no effect** on the dev server. Even force refreshing the page won't work; once applied, the styles are stuck in the `head` as an inline `style` tag

Note that we process components within Browsersync middleware _just_ before Vite gets to it. This was only supported with the latest Vite 2.7 release, so this could be a fixable bug. But the FOUC in particular deters me from using this approach. Injecting `link` tags into the `head` is also much closer to the production experience!

## 2. Use Vite's `transformIndexHtml` to safely inject styles

Turns out, Vite has their own plugin API for slapping elements into the `head`: [transformIndexHtml](https://vitejs.dev/guide/api-plugin.html#transformindexhtml). Here's a one approach I found:

```js
transformIndexHtml(html, ctx, build) {
  const outputPath = path.join(dir.output, ctx.path)
  /** @type {Set<string>} */
  const importedStyles = new Set()
  // note: we need access to the componentAttrStore for these to exist!
  for (const componentAttrs of componentAttrStore.getAllByPage(outputPath)) {
    componentAttrs.importedStyles.forEach((importedStyle) =>
      importedStyles.add(importedStyle),
    )
  }
  return [...importedStyles].map((importedStyle) => ({
    tag: 'link',
    attrs: {
      rel: 'stylesheet',
      href: importedStyle,
    },
  }))
}
```

**Pros:**
- Uses Vite's built-in API to manipulate HTML instead of using our own parser
- Only runs on `.html` files, so we shouldn't hit new XML parsing issues
-  Handles HTML fragments gracefully even if they're missing a `head`, `body`, etc. For example:

```html
<!--input.html-->
<p>lol</p>
{% react 'Slinky' %}
```

```html
<!--_site/output.html-->
<script type="module" crossorigin src="/assets/index.45171407.js"></script>
<link rel="modulepreload" href="/assets/modulepreload-polyfill.b7f2da20.js">
<link rel="modulepreload" href="/assets/react.22b34a2d.js">
<link rel="modulepreload" href="/assets/eagerLoader.13480a8a.js">
<!--yes, link tags outside a `head`. But that's already a risk with JavaScript as you can see above ☝️-->
<link rel="stylesheet" href="/assets/somecoolstyles.css">
<p>lolll</p>

<slinkity-react-mount-point data-s-id="0">
	...
</slinkity-react-mount-point>
```

**Cons:**
- More code complexity. Instead of processing styles where we process our scripts, we now need to store compiled styles in the `componentAttrStore` to get picked up by Vite; this causes some indirection that's tougher to document and maintain overtime. We're also pulling from the `componentAttrStore` within a Vite plugin, so we'll need to 1) hoist it higher in the architecture and 2) ensure we unit test this transform with some injection
- We're magically injecting our own content into the `head` that 11ty users might not expect. Granted, Vite already does so with `modulepreload` tags (see code snippet above), but I also understand that 11ty users are power users. They love total control over the HTML they ship!

## 3. Introduce a required data prop for all layouts
Instead of injecting automatically, we could require 11ty users to manually apply our style tags into the `head` of their document. We could expose a piece of global data called `__slinkity.head` like so:

```html
<!--layout.njk-->
<html>
  <head>
     ...
     {{ __slinkity.head }}
  </head>
  <body>...</body>
</html>
```

This would likely apply an SSR comment (much like our component shortcodes) that we can find-and-replace during the build step.

**Pros:**
- Much easier to implement. Since this piggybacks on our existing approach for component shortcodes, it would only take 1 extra check to find and replace our stylesheet tags
- Gives more control to 11ty users. Using `__slinkity.head`, you can decide where `link` tags are applied, if at all

**Cons:**
- One more thing to add to get components working in your project. Granted, this data prop **is only required if you're importing styles into components via ESM;** aka it's not required when first onboarding to Slinkity. It's a minor annoyance to flag in our component shortcode docs though.

## 4. Some combo of 2 and 3?
We could easily check if you manually applied `__slinkity.head` to your page. This means we could use either approach as necessary:
- if no `__slinkity.head` exists, inject styles into the `head` using a transform
- if `__slinkity.head` does exist, apply styles where specified

This would _not_ solve number 2's con of code complexity though! If anything, I'd only consider this as a fast-follow to number 2 for a bit more flexibility.

## My verdict?

I'm personally split between 2 and 3. 2 offers the most seemless user experience, while 3 trades slight developer friction for a simpler codebase and more power user control. Curious what y'all think @AndrewLeedham @ajcwebdev!

**Comment by ajcwebdev** [comment] 2022-01-04 08:06
Three sounds like the best option to me, especially since it's already very common for frameworks to include some kind of hook into the document head (Svelte, Next, Nuxt, and Redwood all have this ability).

**Comment by Holben888** [comment] 2022-01-05 14:04
Okay, so I _will_ confess this work is blocking renderer work at the moment because it's such a wide refactor. I vote we go with #3 for now since it's the simplest to implement. If we can ditch the `{{ __slinkity.head }}` in a future PR, great! But it seems like a reasonable requirement for the short term.

**Comment by AndrewLeedham** [comment] 2022-01-05 14:10
I agree `{{ __slinkity.head }}` seems like the most 11ty approach, and is less magical.

**Comment by darthmall** [comment] 2022-01-05 15:32
I confess I’m not sure I fully understand the problems with solutions 1 and 2, but 3 seems like a good option to me. As @ajcwebdev mentioned, this is how Svelte has handled things in the past (maybe SvelteKit is taking a different approach, I haven’t been watching carefully); it is easy to understand (I think); gives you a good amount of control with minimal effort.

As for having one more thing you need to set up to get Slinkity working, this seems like the kind of thing that could be handled with templates so that something like `npm init slinkity` creates a project with that placeholder in place. That plus good docs on “how to set up ESM imports for your styles” seems like it should cover your bases pretty well.

**Comment by AleksandrHovhannisyan** [comment] 2022-01-06 13:53
Late to the party—another vote for 3!

**Comment by Holben888** [comment] 2022-01-08 22:52
Alright, looks like everything is ready to go on our end! The XML shebang issue still persists from Vite's end though, but it's more nuanced than I expected. It looks like 11ty's nunjucks parser _comments out_ these XML declarations to successfully parse to HTML. Interesting that Vite attempts to resolve this XML declaration even after it's commented out...

<img width="810" alt="image" src="https://user-images.githubusercontent.com/31811199/148662520-b83d9d74-36af-48fa-a032-bcc78c29273a.png">

In any case, I'd suggest removing these XML headings across your SVGs to get things working @kylesloper. Especially since they're commented out of standard 11ty outputs already, so they aren't having any useful effect.

**Comment by Holben888** [comment] 2022-01-08 22:53
We should investigate that XML comment parsing as a follow-up before closing this issue

**Comment by bholmesdev** [comment] 2024-03-22 01:39
Closing after two long years of progress. It was a privilege to debug with you all 🙏 

I will share that the Slinkity project is no longer maintained. To make this clear to new users, I have archived the repository, and I have updated the project README to reflect the current status.

If the community would like to fork and keep Slinkity alive, all code is open and MIT licensed. I apologize for the radio silence, but I hope this clarifies everything!

**Closed by bholmesdev** 2024-03-22 01:39 UTC
Labels: 🐞 bug
